export default [
    {
        "_id": 345,
        "userName": "SpaceX",
        "handle": "SpaceX",
        "time": "2h",
        "tuit": "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars",
        "userImage": "/images/image_spacex.jpeg",
        "image": "",
        "image_title": "",
        "image_description": "",
        "image_link": "",
        "liked": true,
        "replies": "123",
        "retuits": "432",
        "likes": 2345,
        "dislikes": 213
    },
    {
        "_id": 123,
        "userName": "Elon Musk",
        "handle": "elonmusk",
        "time": "23h",
        "tuit": "Amazing show about @Inspiration4x mission!",
        "userImage": "/images/image_elonmusk.jpeg",
        "image": "/images/image_inspiration4.jpeg",
        "image_title": "Countdown: Inspiration4 Mission to Space | Netflix Official Site",
        "image_description": "From training to launch to landing, this all-access docuseries rides along with the Inspiration4 crew on the first all-civilian orbital space",
        "image_link": "netflix.com",
        "liked": false,
        "replies": "4.2K",
        "retuits": "3.5K",
        "likes": 3700,
        "dislikes": 4444
    },
    {
        "_id": 234,
        "userName": "New York Post",
        "handle": "nypost",
        "time": "10h",
        "tuit": "Grimes seen reading Karl Marx following split with world's richest man Elon Musk trib.al/nx2Gfaq",
        "userImage": "/images/image_nypost.png",
        "image": "/images/image_grimes.jpeg",
        "image_title": "",
        "image_description": "",
        "image_link": "",
        "liked": true,
        "replies": "965",
        "retuits": "2.4K",
        "likes": 4000,
        "dislikes": 420
    },
    {
        "_id": 3423, "topic": "Traffic", "userName": "The Boring Company",
        "handle": "boringcompany", "time": "2h", "userImage": "/images/image_theboringcompany.png",
        "title": "100s of SpaceX Starships land on Mars after a 6 month journey. 1000s of Martian colonists being building Mars Base 1",
        "tuit": "The Boring Company (TBC) is an American infrastructure and tunnel construction services company founded by Elon Musk. Its ongoing and proposed projects are designed for intra-city ('loop') transit systems.",
        "liked": false, "likes": 2345,
        "replies": 123, "retuits": 432,
        "dislikes": 222
    },
];